contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #varcaller channel"
    url: https://nfcore.slack.com/channels/varcaller
    about: Discussion about the nf-core/varcaller pipeline
